package com.covid.fight.warriorproject.entity;

public enum ResourceType {
    AMBULANCE,
    COVID_CAB,
    COVID_AUTO,
    OXYGEN_SELLER,
    PLASMA_DONOR,
    REDMDESIVIR_SELLER,
    MEDICAL_STORE_NUMBER,
    BLOOD_INDIVIDUAL_DONOR,
    BLOOD_BANK,
    GOVT_HELPLINE_NUMBER,
    HOSPITAL_CONTACT_NUMBER,
    PAID_TIFFIN_DELIVERY,
    FREE_FOOD
}
